spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb
    username: root
    password: Sql123.
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
redis:
  database: RedisDB
  password: password
  host: redis-host
  port: 6379


